// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDppOqoi4nk34MK7PlxAojMEYuRjPLyBYk',
    appId: '1:267388579884:web:b15af502b4d33cf7dc6189',
    messagingSenderId: '267388579884',
    projectId: 'myflutterlearningproject',
    authDomain: 'myflutterlearningproject.firebaseapp.com',
    storageBucket: 'myflutterlearningproject.firebasestorage.app',
    measurementId: 'G-4FHQYKMKC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlAknUVoepap7O85-18kb2-_fcPZ9hGek',
    appId: '1:267388579884:android:69004da05a0a046cdc6189',
    messagingSenderId: '267388579884',
    projectId: 'myflutterlearningproject',
    storageBucket: 'myflutterlearningproject.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRwqqDTZA3V4AtWlOUwqH43JADiNv0gFM',
    appId: '1:267388579884:ios:288908955d630660dc6189',
    messagingSenderId: '267388579884',
    projectId: 'myflutterlearningproject',
    storageBucket: 'myflutterlearningproject.firebasestorage.app',
    iosBundleId: 'com.example.mylearningapplication',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRwqqDTZA3V4AtWlOUwqH43JADiNv0gFM',
    appId: '1:267388579884:ios:288908955d630660dc6189',
    messagingSenderId: '267388579884',
    projectId: 'myflutterlearningproject',
    storageBucket: 'myflutterlearningproject.firebasestorage.app',
    iosBundleId: 'com.example.mylearningapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDppOqoi4nk34MK7PlxAojMEYuRjPLyBYk',
    appId: '1:267388579884:web:627e7bd4daea7847dc6189',
    messagingSenderId: '267388579884',
    projectId: 'myflutterlearningproject',
    authDomain: 'myflutterlearningproject.firebaseapp.com',
    storageBucket: 'myflutterlearningproject.firebasestorage.app',
    measurementId: 'G-SE5LBVDHG3',
  );
}
